#!/usr/bin/env bash

# Title: go-get-ssh
# Description: Wrapper for "go get -v -u" using ssh git clone
# Author: William Chanrico
# Date: 07-August-2018

if [[ -z $1 ]]; then
	echo "usage: ${0##*\/} IMPORT_PATH"
	echo "example:"
	echo "         ${0##*\/} github.com/tokopedia/gosample"
	echo ""
	echo "         Will be imported to:"
	echo "         \$GOPATH/src/github.com/tokopedia/gosample"
	exit
fi

# Check if $GOPATH is valid
if [[ -z "${GOPATH}" ]]; then
	echo "\$GOPATH is not set"
	exit
fi

repo_local_path="$GOPATH/src/$1"
repo_remote_ssh_path="git@${1%%/*}:${1#*/}.git"

if [[ ! -d "$repo_local_path" ]]; then
	# Create import directory and cd into it
	mkdir -p $repo_local_path

	# Clone the repository
	git clone $repo_remote_ssh_path .
else
	echo "Repo already exists in $repo_local_path"
	exit
fi

# Change current dir into the repo
cd $repo_local_path

# Run go get -v -u in the repo directory
go get -v -u .

# Echo final imported package's location
echo -e "\nPackage imported: $repo_local_path"